name: Manual Simple Docker Build (GHCR Fallback)

on:
  workflow_dispatch:

jobs:
  simple-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (plain docker)
        run: |
          echo Building image...
          docker build -t ghcr.io/${{ github.repository_owner }}/studentlogin:latest .

      - name: Push
        run: |
          echo Pushing image...
          docker push ghcr.io/${{ github.repository_owner }}/studentlogin:latest

      - name: Summary
        run: 'echo Fallback workflow pushed ghcr.io/${{ github.repository_owner }}/studentlogin:latest >> $GITHUB_STEP_SUMMARY'